instance_class: F2
runtime: nodejs16

handlers:
  - url: /favicon.ico
    static_files: favicon.ico
    require_matching_file: false
    upload: favicon.ico
  - url: .*
    script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 10
  max_concurrent_requests: 40
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: 5000ms
  max_pending_latency: 5000ms

network: {}

#inbound_services:
#  - warmup
